import { Bell } from "lucide-react";
import type { SecurityAlert } from "../types/soc";
import { severityColor } from "../data/sampleData";
import { EmptyState } from "./EmptyState";

interface RecentAlertsTableProps {
  items: SecurityAlert[];
  onRowClick?: (a: SecurityAlert) => void;
}

export function RecentAlertsTable({ items, onRowClick }: RecentAlertsTableProps) {
  if (!items.length) {
    return (
      <EmptyState
        icon={Bell}
        title="No alerts"
        description="Alerts are generated by the detection engine or ingested from your log pipeline."
      />
    );
  }

  return (
    <div className="overflow-hidden rounded-xl border border-white/10 bg-black/20">
      <table className="w-full text-left text-xs">
        <thead className="border-b border-white/10 bg-white/5 text-[10px] font-semibold uppercase tracking-wider text-slate-500">
          <tr>
            <th className="px-3 py-2">ID</th>
            <th className="px-3 py-2">Type</th>
            <th className="px-3 py-2">Severity</th>
            <th className="hidden px-3 py-2 md:table-cell">Source</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5 text-slate-300">
          {items.map((a) => (
            <tr
              key={a.id}
              className={onRowClick ? "cursor-pointer hover:bg-white/5" : ""}
              onClick={() => onRowClick?.(a)}
            >
              <td className="whitespace-nowrap px-3 py-2 font-mono text-cyan-200/90">{a.id}</td>
              <td className="max-w-[180px] truncate px-3 py-2">{a.eventType}</td>
              <td className="px-3 py-2">
                <span style={{ color: severityColor(a.severity) }}>{a.severity}</span>
              </td>
              <td className="hidden font-mono px-3 py-2 text-slate-400 md:table-cell">{a.sourceIp}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
